### ISSUE TITLE
Color suggestion

### ISSUE THREAD

**Issue by lxwndr** [v-svg/dde-dock-clock#3]
The red color does not allow easy viewing; opt for a lighter color.

The highlight of the day in a circle is perfect!

I suggest the adoption of blue (colors that the system - deepin - uses).
![Captura de Tela_Área de Seleção_20191006133443](https://user-images.githubusercontent.com/45263160/66272288-120d7900-e83e-11e9-9e5d-ab3a199d2f15.png)

**Comment by v-svg** [comment]
A good idea! I changed the color of the weekend to the color of the theme:
![DeepinScreenshot_select-area_20191007032030](https://user-images.githubusercontent.com/55928919/66278446-b54ba600-e8b1-11e9-8827-83e6dc1f56a4.png)

Color can be turned off:
![DeepinScreenshot_select-area_20191007032155](https://user-images.githubusercontent.com/55928919/66278450-bb418700-e8b1-11e9-9c2d-79d8eca8b5e6.png)
I will update tomorrow.

**Comment by v-svg** [comment]
New version added.
